services:
  node-clash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-clash-container
    environment:
      - NODE_ENV=production
    ports:
      - "3434:3434"
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "4123:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./drizzle:/docker-entrypoint-initdb.d

volumes:
  pgdata: