import {
  FlameIcon,
  FolderLockIcon,
  KeyRoundIcon,
  LayoutGridIcon,
  ListFilterIcon,
  RadarIcon,
  ScanSearchIcon,
  UmbrellaIcon,
} from 'lucide-react';

import { GameDefenseType } from '@/lib/game-defense';

export const GAME_DEFENSES: GameDefenseType[] = [
  {
    id: 'd-firewall',
    alias: 'Firewall',
    name: 'Firewall',
    desc: 'game-defense.firewall-desc',
    education: 'game-defense.firewall-edu',
    icon: FlameIcon,
    color: {
      primary: 'bg-red-700',
      secondary: 'bg-red-600',
      accent: 'text-red-100',
      strong: 'text-red-1000',
    },
  },
  {
    id: 'd-ids',
    alias: 'Intrusion Detection System',
    name: 'IDS',
    desc: 'game-defense.ids-desc',
    education: 'game-defense.ids-edu',
    icon: RadarIcon,
    color: {
      primary: 'bg-blue-700',
      secondary: 'bg-blue-600',
      accent: 'text-blue-100',
      strong: 'text-blue-1000',
    },
  },
  {
    id: 'd-antivirus',
    alias: 'Antivirus',
    name: 'Antivirus',
    desc: 'game-defense.antivirus-desc',
    education: 'game-defense.antivirus-edu',
    icon: UmbrellaIcon,
    color: {
      primary: 'bg-red-700',
      secondary: 'bg-red-600',
      accent: 'text-red-100',
      strong: 'text-red-1000',
    },
  },
  {
    id: 'd-network-segmentation',
    alias: 'Network Segmentation',
    name: 'Network Segmentation',
    desc: 'game-defense.network-segmentation-desc',
    education: 'game-defense.network-segmentation-edu',
    icon: LayoutGridIcon,
    color: {
      primary: 'bg-teal-700',
      secondary: 'bg-teal-600',
      accent: 'text-teal-100',
      strong: 'text-teal-1000',
    },
  },
  {
    id: 'd-anomaly-detection',
    alias: 'Anomaly Detection',
    name: 'Anomaly Detection',
    desc: 'game-defense.anomaly-detection-desc',
    education: 'game-defense.anomaly-detection-edu',
    icon: ScanSearchIcon,
    color: {
      primary: 'bg-blue-700',
      secondary: 'bg-blue-600',
      accent: 'text-blue-100',
      strong: 'text-blue-1000',
    },
  },
  {
    id: 'd-spam-filter',
    alias: 'Spam Filter',
    name: 'Spam Filter',
    desc: 'game-defense.spam-filter-desc',
    education: 'game-defense.spam-filter-edu',
    icon: ListFilterIcon,
    color: {
      primary: 'bg-blue-700',
      secondary: 'bg-blue-600',
      accent: 'text-blue-100',
      strong: 'text-blue-1000',
    },
  },
  {
    id: 'd-encryption',
    alias: 'Encryption',
    name: 'Encryption',
    desc: 'game-defense.encryption-desc',
    education: 'game-defense.encryption-edu',
    icon: FolderLockIcon,
    color: {
      primary: 'bg-teal-700',
      secondary: 'bg-teal-600',
      accent: 'text-teal-100',
      strong: 'text-teal-1000',
    },
  },
  {
    id: 'd-mfa',
    alias: 'Multi-Factor Authentication',
    name: 'MFA',
    desc: 'game-defense.mfa-desc',
    education: 'game-defense.mfa-edu',
    icon: KeyRoundIcon,
    color: {
      primary: 'bg-red-700',
      secondary: 'bg-red-600',
      accent: 'text-red-100',
      strong: 'text-red-1000',
    },
  },
];
