import {
  AmphoraIcon,
  BandageIcon,
  BookKeyIcon,
  BookLockIcon,
  BracesIcon,
  BrainIcon,
  BugIcon,
  CircleIcon,
  CookieIcon,
  DatabaseBackupIcon,
  DoorOpenIcon,
  EraserIcon,
  EthernetPortIcon,
  FileSearchIcon,
  FishIcon,
  FlameIcon,
  GlobeLockIcon,
  KeyRoundIcon,
  LayoutGridIcon,
  LockIcon,
  LogsIcon,
  NetworkIcon,
  RocketIcon,
  ScrollTextIcon,
  ShieldEllipsisIcon,
  ShieldUserIcon,
  SquareChartGanttIcon,
  VenetianMaskIcon,
  WorkflowIcon,
} from 'lucide-react';

import { GameCardType } from '@/lib/game-card';

export const GAME_CARDS: GameCardType[] = [
  {
    id: 'cas-network-scanning',
    name: 'Network Scanning',
    desc: 'game-card.network-scanning-desc',
    role: 'attacker',
    type: 'stealth',
    icon: NetworkIcon,
    effect: {},
  },
  {
    id: 'cas-social-engineering',
    name: 'Social Engineering',
    desc: 'game-card.social-engineering-desc',
    role: 'attacker',
    type: 'stealth',
    icon: BrainIcon,
    effect: {},
  },
  {
    id: 'cas-port-scanning',
    name: 'Port Scanning',
    desc: 'game-card.port-scanning-desc',
    role: 'attacker',
    type: 'stealth',
    icon: EthernetPortIcon,
    effect: {},
  },
  {
    id: 'cas-vpn-tunneling',
    name: 'VPN Tunneling',
    desc: 'game-card.vpn-tunneling-desc',
    role: 'attacker',
    type: 'stealth',
    icon: GlobeLockIcon,
    effect: {},
  },
  {
    id: 'cas-lateral-movement',
    name: 'Lateral Movement',
    desc: 'game-card.lateral-movement-desc',
    role: 'attacker',
    type: 'stealth',
    icon: WorkflowIcon,
    effect: {},
  },
  {
    id: 'caa-sql-injection',
    name: 'SQL Injection',
    desc: 'game-card.sql-injection-desc',
    role: 'attacker',
    type: 'attack',
    icon: SquareChartGanttIcon,
    effect: {
      nodes: ['nh-database-server', 'nm-web-server'],
      stealTokens: 1,
    },
  },
  {
    id: 'caa-phishing-attack',
    name: 'Phising Attack',
    desc: 'game-card.phishing-attack-desc',
    role: 'attacker',
    type: 'attack',
    icon: FishIcon,
    effect: {
      nodes: ['nl-workstation'],
      stealTokens: 1,
    },
  },
  {
    id: 'caa-zero-day-exploit',
    name: 'Zero-Day Exploit',
    desc: 'game-card.zero-day-exploit-desc',
    role: 'attacker',
    type: 'attack',
    icon: CircleIcon,
    effect: {
      nodes: ['all'],
      stealTokens: 1,
      ignoredDefenses: 3,
    },
  },
  {
    id: 'caa-ransomware-attack',
    name: 'Ransomware Attack',
    desc: 'game-card.ransomware-attack-desc',
    role: 'attacker',
    type: 'attack',
    icon: BugIcon,
    effect: {},
  },
  {
    id: 'caa-man-in-the-middle',
    name: 'Man-in-the-Middle',
    desc: 'game-card.man-in-the-middle-desc',
    role: 'attacker',
    type: 'attack',
    icon: VenetianMaskIcon,
    effect: {},
  },
  {
    id: 'cad-ddos-attack',
    name: 'DDoS Attack',
    desc: 'game-card.ddos-attack-desc',
    role: 'attacker',
    type: 'disrupt',
    icon: RocketIcon,
    effect: {},
  },
  {
    id: 'cad-log-tampering',
    name: 'Log Tampering',
    desc: 'game-card.log-tampering-desc',
    role: 'attacker',
    type: 'disrupt',
    icon: EraserIcon,
    effect: {},
  },
  {
    id: 'cad-backdoor-installation',
    name: 'Backdoor Installation',
    desc: 'game-card.backdoor-installation-desc',
    role: 'attacker',
    type: 'disrupt',
    icon: DoorOpenIcon,
    effect: {},
  },
  {
    id: 'cad-privilege-escalation',
    name: 'Privilege Escalation',
    desc: 'game-card.privilege-escalation-desc',
    role: 'attacker',
    type: 'disrupt',
    icon: ShieldUserIcon,
    effect: {},
  },
  {
    id: 'cad-session-hijacking',
    name: 'Session Hijacking',
    desc: 'game-card.session-hijacking-desc',
    role: 'attacker',
    type: 'disrupt',
    icon: CookieIcon,
    effect: {},
  },
  {
    id: 'cdb-firewall-upgrade',
    name: 'Firewall Upgrade',
    desc: 'game-card.firewall-upgrade-desc',
    role: 'defender',
    type: 'block',
    icon: FlameIcon,
    effect: {
      nodes: ['nh-database-server', 'nm-web-server'],
      addDefense: 'd-firewall',
    },
  },
  {
    id: 'cdb-access-control-policy',
    name: 'Access Control Policy',
    desc: 'game-card.access-control-policy-desc',
    role: 'defender',
    type: 'block',
    icon: LockIcon,
    effect: {},
  },
  {
    id: 'cdb-mfa-implementation',
    name: 'MFA Implementation',
    desc: 'game-card.mfa-implementation-desc',
    role: 'defender',
    type: 'block',
    icon: KeyRoundIcon,
    effect: {
      nodes: ['nm-email-server', 'nl-workstation'],
      addDefense: 'd-mfa',
    },
  },
  {
    id: 'cdb-endpoint-protection',
    name: 'Endpoint Protection',
    desc: 'game-card.endpoint-protection-desc',
    role: 'defender',
    type: 'block',
    icon: BracesIcon,
    effect: {},
  },
  {
    id: 'cdb-network-segmentation',
    name: 'Network Segmentation',
    desc: 'game-card.network-segmentation-desc',
    role: 'defender',
    type: 'block',
    icon: LayoutGridIcon,
    effect: {
      nodes: ['all'],
      ignoreAttack: true,
    },
  },
  {
    id: 'cdd-obfuscation-shield',
    name: 'Obfuscation Shield',
    desc: 'game-card.obfuscation-shield-desc',
    role: 'defender',
    type: 'detect',
    icon: ShieldEllipsisIcon,
    effect: {},
  },
  {
    id: 'cdd-security-awareness',
    name: 'Security Awareness',
    desc: 'game-card.security-awareness-desc',
    role: 'defender',
    type: 'detect',
    icon: BookLockIcon,
    effect: {},
  },
  {
    id: 'cdd-honeypot',
    name: 'Honeypot',
    desc: 'game-card.honeypot-desc',
    role: 'defender',
    type: 'detect',
    icon: AmphoraIcon,
    effect: {},
  },
  {
    id: 'cdd-network-monitoring',
    name: 'Network Monitoring',
    desc: 'game-card.network-monitoring-desc',
    role: 'defender',
    type: 'detect',
    icon: NetworkIcon,
    effect: {},
  },
  {
    id: 'cdd-log-analysis',
    name: 'Log Analysis',
    desc: 'game-card.log-analysis-desc',
    role: 'defender',
    type: 'detect',
    icon: LogsIcon,
    effect: {},
  },
  {
    id: 'cdr-data-recovery-protocol',
    name: 'Data Recovery Protocol',
    desc: 'game-card.data-recovery-protocol-desc',
    role: 'defender',
    type: 'recover',
    icon: DatabaseBackupIcon,
    effect: {},
  },
  {
    id: 'cdr-vulnerability-patching',
    name: 'Vulnerability Patching',
    desc: 'game-card.vulnerability-patching-desc',
    role: 'defender',
    type: 'recover',
    icon: BandageIcon,
    effect: {},
  },
  {
    id: 'cdr-forensic-investigation',
    name: 'Forensic Investigation',
    desc: 'game-card.forensic-investigation-desc',
    role: 'defender',
    type: 'recover',
    icon: FileSearchIcon,
    effect: {},
  },
  {
    id: 'cdr-incident-response',
    name: 'Incident Response',
    desc: 'game-card.incident-response-desc',
    role: 'defender',
    type: 'recover',
    icon: ScrollTextIcon,
    effect: {},
  },
  {
    id: 'cdr-threat-intelligence',
    name: 'Threat Intelligence',
    desc: 'game-card.threat-intelligence-desc',
    role: 'defender',
    type: 'recover',
    icon: BookKeyIcon,
    effect: {},
  },
];
